sdk/Dockerfile

see https://github.com/flutter/flutter/pull/10100/files

expose `FLUTTER_ROOT` as well

---

.cirrus.yml

Fixes https://github.com/cirruslabs/docker-images-flutter/issues/10

Update Flutter to 1.2.1.

---

.cirrus.yml
build_docker.sh
sdk/Dockerfile

See more at https://flutter.dev/docs/development/tools/sdk/releases

expose different versions and channels

---

.cirrus.yml

stable and latest version `v1.5.4-hotfix.2`
- https://flutter.dev/docs/development/tools/sdk/releases?tab=macos

update flutter stable and beta version

---

build_docker.sh
push_docker.sh
web/Dockerfile

Build `-web` tags as well with chromium pre-installed.

Flutter Web Images

---

.cirrus.yml

- https://flutter.dev/docs/development/tools/sdk/releases?tab=macos

update sdk version

---

.cirrus.yml

dev is on v1.12.1

---

.cirrus.yml

Updates all channels to their up-to-date versions as of 1/28/2020.
Not sure if this is the protocol for contributing, so happy to make any modifications.

Bump all versions 1/28/20

---

.cirrus.yml

Updates 
- latest
- stable
- beta
- dev
branches.
This fixes #51

Update FLUTTER_VERSION in cirrus config

---

web/Dockerfile

Enable Flutter Web

---

sdk/Dockerfile

Run flutter doctor --android-licenses

---

sdk/Dockerfile

Update base android image

---

.cirrus.yml

another beta version was released (yes, just a few hours after the last one)

Beta-1.22.0-12.3.pre

---

.cirrus.yml

Closes https://github.com/cirruslabs/docker-images-flutter/issues/112

Bumped version

---

.cirrus.yml

Beta -> 1.26.0-17.6.pre

---

.cirrus.yml

Beta -> 1.26.0-17.7.pre & Dev -> 1.27.0-4.0.pre

Beta -> 1.26.0-17.7.pre & Dev -> 1.27.0-4.0.pre

---

.cirrus.yml

Beta -> 1.26.0-17.8.pre & Dev -> 1.27.0-8.0.pre

Beta -> 1.26.0-17.8.pre & Dev -> 1.27.0-8.0.pre

---

.cirrus.yml

Latest/Stable/Beta -> 2.0.1

---

.cirrus.yml

Beta -> 2.1.0-12.2.pre

---

.cirrus.yml

Update flutter stable 2.0.3

---

sdk/Dockerfile

save ca. 850MB (900M->50M) size.

set git clone depth 1 to decrease code size

---

.cirrus.yml

Beta -> 2.2.0-10.2.pre

---

.cirrus.yml

Beta -> 2.2.0-10.3.pre

---

.cirrus.yml

Both stable and beta channel are now are flutter/flutter@d79295a

build: bump stable and beta channel to 2.2.2

---

.cirrus.yml

- Beta 2.5.0-5.1.pre
- Dev 2.5.0-6.0.pre

Bump Beta & Dev

---

.cirrus.yml

Stable: 2.5.1
Beta: 2.6.0-5.2.pre
Dev: 2.6.0-5.1.pre

Stable , Beta & Dev

---

.cirrus.yml

https://flutter.dev/docs/development/tools/sdk/releases?tab=windows

Update to latest published versions

---

.cirrus.yml

* updates beta to 2.8.0-3.1.pre
* closes: #182

chore: upgrade beta to 2.8.0-3.1.pre

---

.cirrus.yml

Flutter is on fire 🎉 
Upgraded to newest beta: 2.8.0-3.3.pre

chore: update beta version

---

.cirrus.yml

chore: Update latest and stable versions

---

.cirrus.yml

Update latest and stable versions

---

.cirrus.yml

* feat: upgrade flutter version on beta and dev to 2.9.0-0.1.pre
* https://docs.flutter.dev/development/tools/sdk/releases
--- 
Happy New Year 🎉

feat: upgrade flutter version on beta and dev to 2.9.0-0.1.pre

---

.cirrus.yml

- Stable-> 2.10.0
- Beta-> 2.10.0-0.3.pre

Stable-> 2.10.0 || Beta-> 2.10.0-0.3.pre

---

.cirrus.yml

Update according to the newest flutter releases
https://docs.flutter.dev/development/tools/sdk/releases

stable -> flutter 2.10.1

---

.cirrus.yml

Flutter 3.0.3

---

.cirrus.yml

Upgrade to Flutter 3.0.4
Fixes https://github.com/cirruslabs/docker-images-flutter/issues/217

Upgrade to Flutter 3.0.4

---

.cirrus.yml

As per https://docs.flutter.dev/development/tools/sdk/releases.

Update to beta 3.3.0-0.0.pre

---

.cirrus.yml

Upgrade to Flutter 3.3.3

---

.cirrus.yml

Upgrade to Flutter 3.3.4

---

.cirrus.yml

Upgrade to Flutter 3.3.6

---

.cirrus.yml

Bump Flutter version to the `3.3.10` version

#244 bump Flutter version to 3.3.10

---

.cirrus.yml

Bump stable from 3.7.2 to 3.7.3

Bump stable from 3.7.2 to 3.7.3

---

.cirrus.yml

Bump stable to 3.7.4

---

sdk/Dockerfile

Use Android SDK 33

---

.cirrus.yml

Update latest stable & beta versions

Update latest stable & beta versions

---

.cirrus.yml

Thanks for your work! Hope this PR contains everything required for a version bump.

Update flutter version (3.7.9/3.9.0-0.2.pre)

---

.cirrus.yml

Upgrade to Flutter 3.7.10 and 3.9.0-21.0.pre

---

.cirrus.yml

upgrade to Flutter 3.7.11 and 3.10.0-1.1.pre

---

.cirrus.yml

Upgrade to latest Flutter minor release

Upgrade to Flutter 3.10.4

---

.cirrus.yml

chore: bump to Flutter 3.13.2

---

.cirrus.yml

Latest new flutter stable version

feat: upgrade to Flutter 3.13.9

---

.cirrus.yml

https://docs.flutter.dev/release/archive?tab=macos
Thanks for everything.

feat: upgrade to Flutter 3.16.0

---

.cirrus.yml

Upgrade flutter from 3.16.0 to 3.16.1

feat: upgrade flutter from 3.16.0 to 3.16.1

---

.cirrus.yml

Contains important bug fixes
https://docs.flutter.dev/release/archive?tab=macos
Thanks :)

feat: upgrade flutter from 3.16.1 to 3.16.2

---

.cirrus.yml

Update Flutter from 3.16.3 to 3.16.4

chore(deps): update Flutter from 3.16.3 to 3.16.4

---

.cirrus.yml

Update Flutter from 3.16.4 to 3.16.5

chore(deps): update Flutter from 3.16.4 to 3.16.5

---

ci.sh

arm64 platform
